name: DocSearch Scraper

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  docsearch-scrape:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ant-design-blazor'

    steps:
    - uses: actions/checkout@master
    - name: scrape
      uses: darrenjennings/algolia-docsearch-action@master
      with:
        algolia_application_id: ${{ secrets.algolia_application_id }}
        algolia_api_key: ${{ secrets.algolia_api_key }}
        file: '.github/workflows/algolia-config.json'
